/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author maria
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    //Constructor
    public PanelTablero() {
        initComponents();
        //MouseAdapter
        this.addMouseListener(new MouseAdapter() {
            @Override
            //MouseEvent
            public void mousePressed(MouseEvent e) {
                //Clase point
                Point p = e.getPoint();
                moverFicha(p);
            }
        });
    }//Fin del constructor
    
    public void moverFicha(Point p) {
        //Clase point
        imgFicha.setLocation(p);
        System.out.println("Coordenadas : " + p.x + " , " + p.y);
    }//fin del metodo moverFicha

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFicha = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FichaRoja.png"))); // NOI18N
        add(imgFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 40, 50));

        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tablerografico2.png"))); // NOI18N
        add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFicha;
    private javax.swing.JLabel imgFondo;
    // End of variables declaration//GEN-END:variables
}
